# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photocatalog.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'photocatalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12photocatalog.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1d\n\x0c\x43ountRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"4\n\x0cPhotoRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"p\n\rPhotoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"N\n\x14UploadStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cuploaded_ids\x18\x03 \x03(\t2\xd3\x01\n\x13PhotoCatalogService\x12%\n\x05Photo\x12\n.IdRequest\x1a\x0e.PhotoResponse\"\x00\x12+\n\x08\x41\x64\x64Photo\x12\r.PhotoRequest\x1a\x0e.PhotoResponse\"\x00\x12\x31\n\x0cRandomPhotos\x12\r.CountRequest\x1a\x0e.PhotoResponse\"\x00\x30\x01\x12\x35\n\tAddPhotos\x12\r.PhotoRequest\x1a\x15.UploadStatusResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photocatalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDREQUEST']._serialized_start=55
  _globals['_IDREQUEST']._serialized_end=78
  _globals['_COUNTREQUEST']._serialized_start=80
  _globals['_COUNTREQUEST']._serialized_end=109
  _globals['_PHOTOREQUEST']._serialized_start=111
  _globals['_PHOTOREQUEST']._serialized_end=163
  _globals['_PHOTORESPONSE']._serialized_start=165
  _globals['_PHOTORESPONSE']._serialized_end=277
  _globals['_UPLOADSTATUSRESPONSE']._serialized_start=279
  _globals['_UPLOADSTATUSRESPONSE']._serialized_end=357
  _globals['_PHOTOCATALOGSERVICE']._serialized_start=360
  _globals['_PHOTOCATALOGSERVICE']._serialized_end=571
# @@protoc_insertion_point(module_scope)