# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import internal.pb.photocatalog_pb2 as photocatalog__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in photocatalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhotoCatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Photo = channel.unary_unary(
                '/PhotoCatalogService/Photo',
                request_serializer=photocatalog__pb2.IdRequest.SerializeToString,
                response_deserializer=photocatalog__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.AddPhoto = channel.unary_unary(
                '/PhotoCatalogService/AddPhoto',
                request_serializer=photocatalog__pb2.PhotoRequest.SerializeToString,
                response_deserializer=photocatalog__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.RandomPhotos = channel.unary_stream(
                '/PhotoCatalogService/RandomPhotos',
                request_serializer=photocatalog__pb2.CountRequest.SerializeToString,
                response_deserializer=photocatalog__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.AddPhotos = channel.stream_unary(
                '/PhotoCatalogService/AddPhotos',
                request_serializer=photocatalog__pb2.PhotoRequest.SerializeToString,
                response_deserializer=photocatalog__pb2.UploadStatusResponse.FromString,
                _registered_method=True)


class PhotoCatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Photo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RandomPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPhotos(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Photo': grpc.unary_unary_rpc_method_handler(
                    servicer.Photo,
                    request_deserializer=photocatalog__pb2.IdRequest.FromString,
                    response_serializer=photocatalog__pb2.PhotoResponse.SerializeToString,
            ),
            'AddPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPhoto,
                    request_deserializer=photocatalog__pb2.PhotoRequest.FromString,
                    response_serializer=photocatalog__pb2.PhotoResponse.SerializeToString,
            ),
            'RandomPhotos': grpc.unary_stream_rpc_method_handler(
                    servicer.RandomPhotos,
                    request_deserializer=photocatalog__pb2.CountRequest.FromString,
                    response_serializer=photocatalog__pb2.PhotoResponse.SerializeToString,
            ),
            'AddPhotos': grpc.stream_unary_rpc_method_handler(
                    servicer.AddPhotos,
                    request_deserializer=photocatalog__pb2.PhotoRequest.FromString,
                    response_serializer=photocatalog__pb2.UploadStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhotoCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PhotoCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhotoCatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Photo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PhotoCatalogService/Photo',
            photocatalog__pb2.IdRequest.SerializeToString,
            photocatalog__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PhotoCatalogService/AddPhoto',
            photocatalog__pb2.PhotoRequest.SerializeToString,
            photocatalog__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RandomPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PhotoCatalogService/RandomPhotos',
            photocatalog__pb2.CountRequest.SerializeToString,
            photocatalog__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPhotos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/PhotoCatalogService/AddPhotos',
            photocatalog__pb2.PhotoRequest.SerializeToString,
            photocatalog__pb2.UploadStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)